version: "3.9"
services:
    web-api-product:
        image: web-product-api:latest
        container_name: web-api-product
        build:
            context: ../src
            dockerfile: ./Product.Api/Dockerfile
        ports:
            - "5001:5001"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*5001