services:
    api-product:
        image: api-product:latest
        container_name: api-product
        build:
            context: ../
            dockerfile: src/Product.Api/Dockerfile
        ports:
           - "5005:80"  # <- Mapeia a porta 80 do container (que está sendo usada) para 5001 no host
           - "5006:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
        restart: unless-stopped